### ISSUE TITLE
Deprecate mudd-dbs application

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/mudd-dbs#131]
## Task
[Mudd-dbs](https://github.com/pulibrary/mudd-dbs) has been fully migrated to static-tables to support the website migration. This application can be deprecated at this point. 

- [x] Archive copy of the production database on GDrive alongside the static tables just in case a request comes to remove something during the first few months of new website operations. 
 - [x] We DROP the database from staging
 - [x] We DROP the database from prod
 - [x] All database credentials and connection info is removed from princeton_ansible, this repo, and the boxes
- [ ] Archive the github repository

**Comment by kevinreiss** [comment]
I'll do the second step after we actually turn off the machines.
